### ISSUE TITLE
Cannot install under Python 3+

### ISSUE THREAD

**Issue by otakucode** [python-oursql/oursql#1]
Installation under Python 3+ fails immediately because setup.py contains antiquated-style print statements with no parenthesis around the arguments.

**Comment by danmichaelo** [comment]
You need to switch to the `py3k` branch before installing

**Comment by fpeterschmitt** [comment]
Hi,

oursql for Python3 seems to be incompatible with Python2, so, why not creating a dedicated package for Python3?

Like, oursql3 as package name and continue to follow the current version?

The objective would be to have a pypi package installable with setuptools/pip, and a simple dependency.

How would you manage to do so?

**Comment by jamestryan** [comment]
Making an oursql3 sounds like a good idea. I'll do that.

**Comment by jamestryan** [comment]
Done. Now oursql3 exists on pypi
