### ISSUE TITLE
could not compile oursql with mysql 5.7

### ISSUE THREAD

**Issue by fanngyuan** [python-oursql/oursql#3]
could not compile oursql with mysql 5.7.Errors like that:

cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c oursqlx/compat.c -o build/temp.macosx-10.11-intel-2.7/oursqlx/compat.o -I/usr/local/mysql/include -fno-omit-frame-pointer -arch x86_64

In file included from oursqlx/compat.c:55:

oursqlx/_exceptions.c:620:24: error: use of undeclared identifier 'ER_ERROR_FIRST'

```
        if (err >= ER_ERROR_FIRST && err <= ER_ERROR_LAST)

                   ^
```

oursqlx/_exceptions.c:620:49: error: use of undeclared identifier 'ER_ERROR_LAST'

```
        if (err >= ER_ERROR_FIRST && err <= ER_ERROR_LAST)

                                            ^
```

2 errors generated.

error: command 'cc' failed with exit status 1

**Comment by carlostighe** [comment]
see this issue #2 

The answer to this was: 

> This broke because of a change in recent versions of mysql. ER_ERROR_FIRST is defined in /usr/local/include/mysql/mysqld_error.h. This constant was removed somewhere between mysql 5.6.26 and mysql 5.7.9. Switching to mysql 5.6.26 should solve the issue until oursql devs update their code.'
